### ISSUE TITLE
2D keypoint network implementation {Minderer et al. 2019}

### ISSUE THREAD

**Issue by mch5048** [buoyancy99/unsup-3d-keypoints#3]
Hi, thanks for sharing this awesome work to our community!

In the paper, authors compare the proposed method with 2D keypoint representation, which is originally proposed by 
[Minderer et al. 2019](https://proceedings.neurips.cc/paper/2019/file/d82c8d1619ad8176d665453cfb2e55f0-Paper.pdf).

While investigating the code implementation, I got confused by the '2D' argument of the keypoint-based PPO algorithm.
Is parsing with '2D' argument instantiates the representation learning proposed by Minderer et al. or just the 2D fraction of this work?
From the code, it seems the 2D version of the keypoint network is not related to that of Minderer et al.

Thanks for your help in advance!

**Comment by buoyancy99** [comment]
2D version here refers to learning keypoints via the method specified by the box "Keypoint Detector" in Figure 1 of [Minderer et al. 2019](https://proceedings.neurips.cc/paper/2019/file/d82c8d1619ad8176d665453cfb2e55f0-Paper.pdf)

The parts outside the "Keypoint Detector" is discarded as they are used for dynamics instead of keypoint learning.

Please close the issue if the above explanation answers your question. If you have further questions, I prefer communication through emails. Github issue page should reserved for questions about code.

**Comment by mch5048** [comment]
Thanks for quick response. Now I understand the code architecture. I'll close this issue and contact you via email if I encounter further questions. Thanks again.
